{% set version = "0.7.2" %}

package:
  name: cligj
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cligj/cligj-{{ version }}.tar.gz
  sha256: a4bc13d623356b373c2c27c53dbd9c68cae5d526270bfa71f6c6fa69669c6b27

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python >=3.6
    - pip
    - wheel
    - setuptools
    - click >=4.0
  run:
    - python >=3.6
    - click >=4.0

test:
  imports:
    - cligj

   commands:
    - pip check

about:
  home: https://github.com/mapbox/cligj
  license: BSD 3-Clause
  license_family: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Click params for commmand line interfaces to GeoJSON.'
  dev_url: https://github.com/mapbox/cligj
  doc_url: https://github.com/mapbox/cligj/blob/master/README.rst

extra:
  recipe-maintainers:
    - ocefpaf
