travis:
  secure:
    BINSTAR_TOKEN: VQmNczSNr2GhI2362estOw57ofdovs7ceJeVzu88IuaCxE59bZq+x27zUOAyoWsIVFENY+3DBnbTSJotJttkFobMH7Q2a2HdCjhpXad90T1m2zAmQbbr4j2AFIcIAREDJfp0tR0ncXYs5yGk7/D84i6e1QTU5SeTRI/2B7+Ed94881gfBBZ2svdjCqguZNWNBfAPEoTsxuATp0rqCtoupVXOmm9tUiixRZ0/vn0pbDWOXDb/3im+Aw86RPXA9rXG98w+hqW45HWH4EUDNxKE0f4QuUMZaaz2+P8bIe1EK6RbBG+Q0m+VqvkSFchGl2/8HUVwhXwUvb6rJxVn5bkkvSge6REf1HDiz27VGdD37rpBQ6AgH7108Z2izGkZSGchht+gv1Q1RdfXnzoj8Ors7ArNfoZrQ25jcb1znOmdqCT8tAvTPozKaPymbFiYC0XxWluHp4Ky87HrqB2bQwJbIWEQ0yJVfq9PYSzXwuJN7Pf8onxDaFzwHfd3jFWe276HFem6gGF6xVlg+KhShGMAZdaP2PNqh0HtiRNxjQcv5gqHzpwEyZ5L6+OIYhWCWQNxwLo+AdX2vbUD/lqx0P9pOpJs/GRQdsl0j6rOtp1NVVX71oo2vjb1T6gJWcdBYtiRm1Bc7R53ilpt92njfHjbfC/kbhJuVPM+2nXmDtGplSU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
